### ISSUE TITLE
RestoreSkins doesn't work

### ISSUE THREAD

**Issue by Feerko** [games647/ChangeSkin#104] opened 2017-11-24 17:54 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
When a player enters the server does not get his skins.

### What behaviour is expected:
[//]: # (What did you expect?)
The player gets his skin.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Join with premium nickname

### Plugin list:
[//]: # (This can be found by running `/pl`)
Authme, FastLogin, ChangeSkin

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number , SQLite/MySQL, ...)
Bungeecord, MySQL

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
3.0

### Error Log:
There is no errors

### Configuration:
[//]: # (remember to delete any sensitive data)
I just set restoreSkins to true

**Comment by games647** [comment] 2017-11-24 19:38
Duplicate of #96?

**Comment by Feerko** [comment] 2017-11-24 19:58
No, /setskin Feerko works for me, but if i delete me from database and rejoin the server i don't get my default skin and i'm steve.

**Comment by Feerko** [comment] 2017-11-24 19:58
I'm using FastLogin and I'm premium.

**Comment by Feerko** [comment] 2017-11-25 16:28
any news?

**Comment by Feerko** [comment] 2017-11-25 19:49
@games647 can you fix it? This is the last bug. Thanks!

**Closed** 2017-11-26 16:09 UTC
Labels: bug
