### ISSUE TITLE
ChangeSkin doesn't work on 1.18.2

### ISSUE THREAD

**Issue by PrzemekSwiderski** [games647/ChangeSkin#249] opened 2022-04-04 22:15 UTC
### What behavior is observed:
Player [even op] is kicked from server. Bug only on 1.18.2 - works good on 1.18.1

### What behavior is expected:
Skin changed/updated

### Steps/models to reproduce:
type command: /skin nick newSkinNick

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Bungecord 1.18.2
PaperSpigot 1.18.2 
MariaDB

### Plugin version or build number (don't write latest):
#336

### Server Log:
https://gist.github.com/PrzemekSwiderski/9aabbfebe9941b86f19b0cc717f6eb57

### Configuration:
https://gist.github.com/PrzemekSwiderski/91fddb884ddb901ac5ff4a5d0d64b453

**Comment by PrzemekSwiderski** [comment] 2022-04-04 22:15
Can you also update repo?

**Comment by PrzemekSwiderski** [comment] 2022-04-04 22:27
This error also happens on Spigot Server (without bungee)

**Comment by PrzemekSwiderski** [comment] 2022-04-04 23:12
After login I have changed skin.

**Comment by games647** [comment] 2022-04-05 03:14
Could you please test without any other plugins.

**Comment by PrzemekSwiderski** [comment] 2022-04-05 09:38
Same bug (kick after 3-4 sec)
https://gist.github.com/PrzemekSwiderski/ba1b93c3c2010b275f0648e5067f0d7d

**Comment by games647** [comment] 2022-04-05 10:29
The error doesn't sound related to ChangeSkin. Which version of ProtocolLib do you use and did you tried to update it?

**Comment by PrzemekSwiderski** [comment] 2022-04-05 12:08
`> protocol version
[14:08:29 INFO]: ProtocolLib v4.8.0
[14:08:29 INFO]: Authors: dmulloy2 and Comphenix
[14:08:29 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues
`

this is newest (downloaded yesterday) version

**Comment by games647** [comment] 2022-04-07 12:19
Duplicate of #247

**Closed by games647** 2022-04-07 12:19 UTC
Labels: bug
